name: english_lessons_app
description: "A new Flutter project for English lessons app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0' # ← تم تعديله هنا
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.25.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  google_fonts: ^6.1.0
  flutter_pdfview: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  lint: ^2.0.0

flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-Italic.ttf
          style: italic
    - family: Taha
      fonts:
        - asset: fonts/Taha.ttf
  uses-material-design: true